name: Build prebuilt APK

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '12.1'
    paths-ignore:
      - '**.mkdn'
      - '.**'
  pull_request:
    paths-ignore:
      - '**.mkdn'
      - '.**'
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: false
        default: 'Workflow dispatch'

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Rename artifact
        if: ${{ !github.event.pull_request }}
        run: |
          oldArtifactPath="app/build/outputs/apk/release/app-release-unsigned.apk"
          newArtifactPath="app/build/outputs/apk/release/Updater.apk"
          echo "ARTIFACT_PATH=$newArtifactPath" >> $GITHUB_ENV
          mv "$oldArtifactPath" "$newArtifactPath"
